export const SET_AUTH_DATA = 'SET_AUTH_DATA';
export const ON_CHANGE_AUTH_FORM = 'ON_CHANGE_AUTH_FORM';

export const REQUEST_REPO_LIST = 'REQUEST_REPO_LIST';
export const RECEIVE_REPO_LIST = 'RECEIVE_REPO_LIST';
export const ERROR_REPO_LIST = 'ERROR_REPO_LIST';
