export const REQUEST_REPO_LIST = 'REQUEST_REPO_LIST';
export const RECEIVE_REPO_LIST = 'RECEIVE_REPO_LIST';
export const ERROR_REPO_LIST = 'ERROR_REPO_LIST';

export const REQUEST_DELETE_REPO = 'REQUEST_DELETE_REPO';
export const RECEIVE_DELETE_REPO = 'RECEIVE_DELETE_REPO';
export const ERROR_DELETE_REPO = 'ERROR_DELETE_REPO';
